language: node_js
node_js:
  - "5.7.0"
before_script:
  - "npm install"
  - "tsd reinstall"
sudo: false
notifications:
  email:
    - touchdevelop-build@microsoft.com
cache:
  directories:
    - node_modules
    - typings
addons:
  apt:
    packages:
      - libusb-1.0-0-dev
